### ISSUE TITLE
Simplify error handling

### ISSUE THREAD

**Issue by xuchunyang** [twlz0ne/elpl#2]
Should

https://github.com/twlz0ne/elpl/blob/43a30f4ebb5d6f6b04fd7ab31dfdde487a5319cf/elpl.el#L60-L63

be simplified to

```el
(condition-case err
    ...
  (end-of-file)
  (err
   (setq s "")
   (print err)))
```

It seems both of them are doing the same thing: for `end-of-file` do nothing.

**Comment by twlz0ne** [comment]
Thank you.
I didn't know these before.

But the simplified code can't pass the test https://github.com/twlz0ne/elpl/blob/master/elpl-test.el

**Comment by xuchunyang** [comment]
There is a type in my code, the branch to handle the `error` error should use `error` not `err`.
