### ISSUE TITLE
Hello! Why this and not ielm?

### ISSUE THREAD

**Issue by Trevoke** [twlz0ne/elpl#6]
emacs already ships with something called `ielm` (`M-x ielm`), what is a good reason for me to use this package instead?

**Comment by twlz0ne** [comment]
The code you evaluate in elpl will not affect the current Emacs.

![elpl-vs-ielm](https://user-images.githubusercontent.com/2653486/58870304-8bf7ef00-86f2-11e9-8332-01d11e4dd52c.png)

**Comment by Trevoke** [comment]
Got it, thank you!
